### ISSUE TITLE
Vertical sharding of Driver location tracking

### ISSUE THREAD

**Issue by NikithShetty** [nammayatri/nammayatri#860]
In effort to isolate driver location tracking load from affecting main trip transactions, Driver location tracking should be separated into an independent module with its own data source.

**Proposed solution**
Proposing the following changes to the current location tracking:
![Screenshot 2023-05-11 at 18 34 45](https://github.com/nammayatri/nammayatri/assets/14048423/dffde5a9-c0fb-4a77-88b9-1457943e6fdc)

We can create a separate service which will handle the driver location updates and driver pool computation.

Tasks

- [x] [Split driver pool compute join query to point queries and add `merchantId` and `vehicleVariant` columns to `DriverLocation` table.](https://github.com/nammayatri/nammayatri/issues/861)
- [x] [Move `DriverLocation` table to new DB instance, i.e., application needs to connect to `LocationTrackingDb` instance (separate configs)](https://github.com/nammayatri/nammayatri/issues/862)
- [ ] [Implement interface for driver tracking module and move driver tracking code to this module](https://github.com/nammayatri/nammayatri/issues/863)
