### ISSUE TITLE
Add Nix support

### ISSUE THREAD

**Issue by srid** [nammayatri/nammayatri#9]
Enable building and developing Nammayatri using [Nix](https://zero-to-nix.com/) (using [haskell-flake](https://haskell.flake.page/)). We will also port the project to GHC 8.10.[^nixpkgs]

[^nixpkgs]: Mainly because 8.8 no longer builds on nixpkgs.

Also,

- Build the docker image using Nix
- Add Github Actions workflow to run the Nix builds in CI
- Autoformatting and linting checks to be done by Nix

**Tasks**

- [x] Port mobility-core to GHC 8.10 https://github.com/nammayatri/shared-kernel/pull/12
- [x] Port nammayatri to GHC 8.10 https://github.com/nammayatri/nammayatri/pull/12
- [x] Add `flake.nix` to nammayatri and `nix build` everything
  - [x] Decouple to `Backend/flake-module.nix`
- [x] Build docker image using Nix
- [x] Add treefmt-nix, for ormolu and hlint
  - [x] https://github.com/nammayatri/nammayatri/pull/29
- [x] Simplify `haskell-overrides.nix` using https://github.com/srid/haskell-flake/pull/87
- [x] Review HLS support https://github.com/nammayatri/nammayatri/pull/35
- [x] Add Github Actions CI #16 
  - [x] Enable cachix
  - [x] Use an official cache, and add to README
- [x] Documentation (add to README, etc.)

**Additional tasks**

- [x] Decouple overrides to other repos
- [ ] Add x86 macos builder to CI
  - [ ] Push intel mac cache to cachix using https://github.com/juspay/cachix-push/issues/2

Further Nix work will happen in #30

**Comment by srid** [comment]
Initial Nix support merged already. For nixifying development workflow, and running backend locally via Nix, see: https://github.com/nammayatri/nammayatri/issues/30
